name: Deploy Background Jobs

on:
  push:
    branches:
      - main
    paths:
      - "packages/jobs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - name: "production"
            access_token: TRIGGER_ACCESS_TOKEN
            project_id: TRIGGER_PROJECT_ID
          - name: "govcloud"
            access_token: TRIGGER_ACCESS_TOKEN
            project_id: GOVCLOUD_TRIGGER_PROJECT_ID

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build:packages

      - name: 🚀 Deploy Trigger.dev (${{ matrix.environment.name }})
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets[matrix.environment.access_token] }}
          TRIGGER_PROJECT_ID: ${{ secrets[matrix.environment.project_id] }}
        run: |
          cd packages/jobs
          npx trigger.dev@3.3.12 deploy
